baseURL = 'https://shagen.me'
languageCode = 'en-us'
title = 'shagen.me'
theme = 'plague'

# add vim (there should be a += in toml...)
[security]
  [security.exec]
  allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^vim$', '^npx$', '^postcss$', '^tailwindcss$']


[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/brianreumere/plague"

[params]
  siteHeaderText = "shagen.me"
  siteFooterText = "created with &#10084;&#65039; in Hoggene"
  colors = "default"
  CustomStylesheet = "/css/custom.css"

[params.hcard]
   fullName = "sdk"

[frontmatter]
  date = [':filename', ':default']
