baseURL = 'https://shagen.me'
languageCode = 'en-us'
title = 'Personal Website of Stefan Hagen'
theme = 'plague'

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/brianreumere/plague"

[params]
  siteHeaderText = "Stefan Hagen / sdk"
  siteFooterText = ""
  colors = "default"

[params.hcard]
   fullName = "Stefan Hagen"

[frontmatter]
  date = [':filename', ':default']
